import type { Document, ExtractionResult, Automation, ActivityItem, AIInsight } from "./types";

export const mockDocuments: Document[] = [
  {
    id: "doc_001",
    name: "Invoice_Acme_Corp_Q4-2025.pdf",
    type: "invoice",
    status: "completed",
    size: 248320,
    pages: 2,
    uploadedAt: "2025-12-18T09:24:00Z",
    processedAt: "2025-12-18T09:24:38Z",
    confidence: 98,
    extractedFields: 14,
    summary: "Invoice from Acme Corp for $12,450.00 due January 15, 2026. Professional services contract Q4 2025.",
  },
  {
    id: "doc_002",
    name: "Resume_Sarah_Mitchell_SeniorDev.pdf",
    type: "resume",
    status: "completed",
    size: 186420,
    pages: 3,
    uploadedAt: "2025-12-17T14:12:00Z",
    processedAt: "2025-12-17T14:12:52Z",
    confidence: 96,
    extractedFields: 22,
    summary: "Senior Full-Stack Developer with 8+ years experience in React, Node.js, Python. Previously at Google and Stripe.",
  },
  {
    id: "doc_003",
    name: "Contract_NDA_TechVentures_2025.pdf",
    type: "contract",
    status: "completed",
    size: 524288,
    pages: 8,
    uploadedAt: "2025-12-17T11:30:00Z",
    processedAt: "2025-12-17T11:31:14Z",
    confidence: 94,
    extractedFields: 18,
    summary: "Non-disclosure agreement between TechVentures Inc. and DigitalFlow Ltd. Effective December 1, 2025.",
  },
  {
    id: "doc_004",
    name: "Q3_Financial_Report_2025.pdf",
    type: "report",
    status: "completed",
    size: 1048576,
    pages: 24,
    uploadedAt: "2025-12-16T16:45:00Z",
    processedAt: "2025-12-16T16:47:02Z",
    confidence: 91,
    extractedFields: 31,
    summary: "Q3 2025 financial report showing 23% revenue growth YoY. Net profit $4.2M. Strong performance in EMEA markets.",
  },
  {
    id: "doc_005",
    name: "Invoice_PixelWorks_Studio_Nov2025.pdf",
    type: "invoice",
    status: "completed",
    size: 156200,
    pages: 1,
    uploadedAt: "2025-12-16T10:20:00Z",
    processedAt: "2025-12-16T10:20:29Z",
    confidence: 99,
    extractedFields: 12,
    summary: "Invoice from PixelWorks Studio for $3,800.00. Design services for brand refresh project.",
  },
  {
    id: "doc_006",
    name: "Resume_James_Park_DataScientist.pdf",
    type: "resume",
    status: "processing",
    size: 214560,
    pages: 2,
    uploadedAt: "2025-12-18T09:45:00Z",
    confidence: 0,
    extractedFields: 0,
    summary: "",
  },
  {
    id: "doc_007",
    name: "Partnership_Agreement_Nexus_2025.pdf",
    type: "contract",
    status: "completed",
    size: 786432,
    pages: 12,
    uploadedAt: "2025-12-15T08:30:00Z",
    processedAt: "2025-12-15T08:32:41Z",
    confidence: 92,
    extractedFields: 24,
    summary: "Strategic partnership agreement between Nexus Technologies and InnovateLabs. 3-year term, $500K joint venture.",
  },
  {
    id: "doc_008",
    name: "Annual_Report_GlobalTech_2024.pdf",
    type: "report",
    status: "failed",
    size: 5242880,
    pages: 68,
    uploadedAt: "2025-12-14T15:00:00Z",
    confidence: 0,
    extractedFields: 0,
    summary: "",
  },
];

export const mockExtractionResults: Record<string, ExtractionResult> = {
  doc_001: {
    documentId: "doc_001",
    documentType: "invoice",
    fields: [
      { key: "invoice_number", value: "INV-2025-4891", confidence: 99, type: "string" },
      { key: "company_name", value: "Acme Corporation", confidence: 98, type: "string" },
      { key: "company_address", value: "1200 Market Street, San Francisco, CA 94102", confidence: 95, type: "string" },
      { key: "client_name", value: "DigitalFlow Ltd.", confidence: 99, type: "string" },
      { key: "issue_date", value: "2025-12-15", confidence: 99, type: "date" },
      { key: "due_date", value: "2026-01-15", confidence: 99, type: "date" },
      { key: "subtotal", value: 10875.00, confidence: 98, type: "currency" },
      { key: "tax_rate", value: "14.5%", confidence: 97, type: "string" },
      { key: "tax_amount", value: 1576.88, confidence: 98, type: "currency" },
      { key: "total_amount", value: 12451.88, confidence: 99, type: "currency" },
      { key: "currency", value: "USD", confidence: 99, type: "string" },
      { key: "payment_terms", value: "Net 30", confidence: 96, type: "string" },
      { key: "bank_account", value: "****4821", confidence: 94, type: "string" },
      { key: "services", value: ["Consulting Q4", "Platform Integration", "Technical Support"], confidence: 93, type: "array" },
    ],
    rawJson: {
      invoice_number: "INV-2025-4891",
      company: { name: "Acme Corporation", address: "1200 Market Street, San Francisco, CA 94102", tax_id: "US94-1234567" },
      client: { name: "DigitalFlow Ltd.", address: "42 Innovation Drive, Austin, TX 78701" },
      dates: { issued: "2025-12-15", due: "2026-01-15" },
      financials: { subtotal: 10875.00, tax: 1576.88, total: 12451.88, currency: "USD" },
      line_items: [
        { description: "Q4 2025 Consulting Services", quantity: 1, unit_price: 7500.00, total: 7500.00 },
        { description: "Platform Integration — Phase 2", quantity: 1, unit_price: 2375.00, total: 2375.00 },
        { description: "Technical Support (40h)", quantity: 40, unit_price: 25.00, total: 1000.00 },
      ],
    },
    summary: "This is a Q4 2025 invoice from Acme Corporation to DigitalFlow Ltd. totaling $12,451.88 USD. It covers professional consulting services, platform integration work, and technical support hours. Payment is due by January 15, 2026 with Net 30 terms.",
    keyInsights: [
      "Invoice total of $12,451.88 is within normal range for Q4 services",
      "Payment due in 28 days — recommend scheduling payment",
      "Tax rate of 14.5% applied correctly to subtotal",
      "Three separate service lines identified",
    ],
    actionItems: [
      "Schedule payment before January 15, 2026",
      "Verify bank account ending ****4821 is correct",
      "File invoice under Q4 2025 vendor records",
    ],
    warnings: [
      "Tax ID not visible in document — may need verification",
    ],
    confidence: 98,
    processingTime: 1840,
  },
  doc_002: {
    documentId: "doc_002",
    documentType: "resume",
    fields: [
      { key: "full_name", value: "Sarah Mitchell", confidence: 99, type: "string" },
      { key: "email", value: "sarah.mitchell@email.com", confidence: 99, type: "email" },
      { key: "phone", value: "+1 (415) 555-0192", confidence: 98, type: "phone" },
      { key: "location", value: "San Francisco, CA", confidence: 97, type: "string" },
      { key: "current_title", value: "Senior Full-Stack Developer", confidence: 99, type: "string" },
      { key: "years_experience", value: 8, confidence: 95, type: "number" },
      { key: "current_company", value: "Stripe", confidence: 98, type: "string" },
      { key: "education_degree", value: "B.Sc. Computer Science", confidence: 98, type: "string" },
      { key: "education_school", value: "Stanford University", confidence: 99, type: "string" },
      { key: "education_year", value: "2016", confidence: 97, type: "string" },
      { key: "primary_skills", value: ["React", "TypeScript", "Node.js", "Python", "AWS", "PostgreSQL"], confidence: 97, type: "array" },
      { key: "languages", value: ["English (Native)", "French (Fluent)", "Spanish (Conversational)"], confidence: 95, type: "array" },
      { key: "previous_companies", value: ["Google", "Stripe", "Airbnb (Internship)"], confidence: 96, type: "array" },
      { key: "linkedin", value: "linkedin.com/in/sarahmitchell", confidence: 93, type: "string" },
      { key: "github", value: "github.com/smitchell-dev", confidence: 94, type: "string" },
      { key: "salary_expectation", value: "$180,000–$220,000", confidence: 72, type: "string" },
    ],
    rawJson: {
      personal: { name: "Sarah Mitchell", email: "sarah.mitchell@email.com", phone: "+1 (415) 555-0192", location: "San Francisco, CA" },
      summary: "Senior Full-Stack Developer with 8 years of experience building scalable web applications at Google and Stripe.",
      experience: [
        { company: "Stripe", title: "Senior Software Engineer", period: "2022–Present", description: "Led payment infrastructure team, handling $2B+ annual transaction volume." },
        { company: "Google", title: "Software Engineer II", period: "2018–2022", description: "Built features for Google Workspace used by 3M+ enterprise customers." },
      ],
      skills: { frontend: ["React", "TypeScript", "Next.js"], backend: ["Node.js", "Python", "Go"], databases: ["PostgreSQL", "Redis", "MongoDB"], cloud: ["AWS", "GCP"] },
    },
    summary: "Sarah Mitchell is a highly qualified Senior Full-Stack Developer with 8 years of experience at top-tier companies including Google and Stripe. She holds a CS degree from Stanford and has expertise across the full tech stack from React/TypeScript to Python/Go with strong cloud infrastructure knowledge.",
    keyInsights: [
      "FAANG experience (Google) — strong technical signal",
      "8 years experience — senior level with leadership potential",
      "Stanford CS degree — top-tier academic background",
      "Multilingual — valuable for international roles",
      "Active GitHub presence detected",
    ],
    actionItems: [
      "Schedule technical screening interview",
      "Verify references at Google and Stripe",
      "Confirm salary expectations match budget ($180K–$220K)",
      "Check portfolio at github.com/smitchell-dev",
    ],
    warnings: [
      "Salary range at upper budget threshold — negotiate carefully",
    ],
    confidence: 96,
    processingTime: 2240,
  },
};

export const mockAutomations: Automation[] = [
  {
    id: "auto_001",
    name: "Invoice Processing",
    description: "Automatically extract vendor details, amounts, dates, and line items from invoices. Export to accounting software.",
    icon: "FileText",
    documentsProcessed: 1284,
    lastRun: "2025-12-18T09:24:00Z",
    status: "active",
    category: "Finance",
    schema: {
      invoice_number: "string",
      vendor_name: "string",
      total_amount: "currency",
      due_date: "date",
      tax_amount: "currency",
      line_items: "array",
    },
  },
  {
    id: "auto_002",
    name: "Resume Screening",
    description: "Parse CVs and resumes to extract skills, experience, education. Score candidates against job requirements automatically.",
    icon: "User",
    documentsProcessed: 847,
    lastRun: "2025-12-17T14:12:00Z",
    status: "active",
    category: "HR",
    schema: {
      full_name: "string",
      email: "email",
      years_experience: "number",
      skills: "array",
      education: "string",
      current_company: "string",
    },
  },
  {
    id: "auto_003",
    name: "Contract Analyzer",
    description: "Extract key contract clauses, parties, terms, obligations, and risk flags from legal documents.",
    icon: "Scale",
    documentsProcessed: 312,
    lastRun: "2025-12-17T11:30:00Z",
    status: "active",
    category: "Legal",
    schema: {
      parties: "array",
      effective_date: "date",
      expiry_date: "date",
      total_value: "currency",
      obligations: "array",
      termination_clause: "string",
    },
  },
  {
    id: "auto_004",
    name: "Financial Report Parser",
    description: "Extract KPIs, metrics, revenue figures, and trends from quarterly and annual financial reports.",
    icon: "BarChart",
    documentsProcessed: 156,
    lastRun: "2025-12-16T16:45:00Z",
    status: "active",
    category: "Finance",
    schema: {
      revenue: "currency",
      net_profit: "currency",
      growth_rate: "number",
      key_metrics: "array",
      period: "string",
      highlights: "array",
    },
  },
  {
    id: "auto_005",
    name: "Medical Records Extractor",
    description: "Parse patient records, lab results, and medical reports for healthcare data management.",
    icon: "HeartPulse",
    documentsProcessed: 89,
    lastRun: "2025-12-15T09:00:00Z",
    status: "paused",
    category: "Healthcare",
    schema: {
      patient_name: "string",
      date_of_birth: "date",
      diagnosis: "string",
      medications: "array",
      physician: "string",
    },
  },
  {
    id: "auto_006",
    name: "Purchase Order Processor",
    description: "Extract supplier info, item lists, quantities, and pricing from purchase order documents.",
    icon: "ShoppingCart",
    documentsProcessed: 0,
    status: "draft",
    category: "Procurement",
    schema: {
      po_number: "string",
      supplier: "string",
      items: "array",
      total: "currency",
      delivery_date: "date",
    },
  },
];

export const mockActivityItems: ActivityItem[] = [
  {
    id: "act_001",
    type: "extraction",
    documentName: "Invoice_Acme_Corp_Q4-2025.pdf",
    documentType: "invoice",
    timestamp: "2025-12-18T09:24:38Z",
    status: "success",
    details: "14 fields extracted — 98% confidence",
  },
  {
    id: "act_002",
    type: "upload",
    documentName: "Resume_James_Park_DataScientist.pdf",
    documentType: "resume",
    timestamp: "2025-12-18T09:45:00Z",
    status: "success",
    details: "214 KB — processing started",
  },
  {
    id: "act_003",
    type: "export",
    documentName: "Invoice_Acme_Corp_Q4-2025.pdf",
    documentType: "invoice",
    timestamp: "2025-12-18T09:26:00Z",
    status: "success",
    details: "Exported to CSV",
  },
  {
    id: "act_004",
    type: "extraction",
    documentName: "Resume_Sarah_Mitchell_SeniorDev.pdf",
    documentType: "resume",
    timestamp: "2025-12-17T14:12:52Z",
    status: "success",
    details: "22 fields extracted — 96% confidence",
  },
  {
    id: "act_005",
    type: "automation",
    documentName: "Contract_NDA_TechVentures_2025.pdf",
    documentType: "contract",
    timestamp: "2025-12-17T11:31:14Z",
    status: "success",
    details: "Contract Analyzer — 18 clauses identified",
  },
  {
    id: "act_006",
    type: "analysis",
    documentName: "Q3_Financial_Report_2025.pdf",
    documentType: "report",
    timestamp: "2025-12-16T16:47:02Z",
    status: "success",
    details: "31 KPIs extracted — AI summary generated",
  },
  {
    id: "act_007",
    type: "extraction",
    documentName: "Annual_Report_GlobalTech_2024.pdf",
    documentType: "report",
    timestamp: "2025-12-14T15:12:00Z",
    status: "error",
    details: "File too large — processing failed",
  },
  {
    id: "act_008",
    type: "export",
    documentName: "Partnership_Agreement_Nexus_2025.pdf",
    documentType: "contract",
    timestamp: "2025-12-15T08:35:00Z",
    status: "success",
    details: "Exported to JSON + Notion",
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    type: "success",
    title: "Invoice Verified",
    description: "All financial figures cross-validated. Tax calculations are accurate. No anomalies detected.",
    confidence: 98,
  },
  {
    type: "warning",
    title: "Missing Tax ID",
    description: "Vendor tax identification number not found in document. May require manual verification before payment.",
    confidence: 85,
  },
  {
    type: "info",
    title: "Payment Due Soon",
    description: "Invoice INV-2025-4891 is due in 28 days. Recommend scheduling payment this week.",
    confidence: 99,
    entities: ["January 15, 2026", "Net 30", "$12,451.88"],
  },
  {
    type: "info",
    title: "Similar Invoices Found",
    description: "3 previous invoices from Acme Corporation found in database. Average amount: $10,200.",
    confidence: 91,
    entities: ["Acme Corporation", "$10,200 avg"],
  },
];

export const mockDashboardMetrics = [
  { label: "Documents Processed", value: "2,847", change: 18.4, changeLabel: "vs last month", trend: "up" as const, icon: "FileText" },
  { label: "Extraction Accuracy", value: "96.2%", change: 2.1, changeLabel: "vs last month", trend: "up" as const, icon: "Target" },
  { label: "Automations Run", value: "689", change: 31.2, changeLabel: "vs last month", trend: "up" as const, icon: "Zap" },
  { label: "Time Saved", value: "142h", change: 24.8, changeLabel: "vs last month", trend: "up" as const, icon: "Clock" },
];

export const mockChartData = {
  documentTypes: [
    { name: "Invoices", value: 1284, color: "#6366f1" },
    { name: "Resumes", value: 847, color: "#8b5cf6" },
    { name: "Contracts", value: 456, color: "#14b8a6" },
    { name: "Reports", value: 260, color: "#f59e0b" },
  ],
  weeklyActivity: [
    { day: "Mon", documents: 42, extractions: 38 },
    { day: "Tue", documents: 58, extractions: 54 },
    { day: "Wed", documents: 71, extractions: 68 },
    { day: "Thu", documents: 49, extractions: 45 },
    { day: "Fri", documents: 83, extractions: 79 },
    { day: "Sat", documents: 24, extractions: 21 },
    { day: "Sun", documents: 18, extractions: 16 },
  ],
  confidenceTrend: [
    { month: "Jul", accuracy: 91.2 },
    { month: "Aug", accuracy: 92.8 },
    { month: "Sep", accuracy: 93.4 },
    { month: "Oct", accuracy: 94.1 },
    { month: "Nov", accuracy: 95.3 },
    { month: "Dec", accuracy: 96.2 },
  ],
};
