import type { Document, ExtractionResult, Automation, ActivityItem, AIInsight } from "./types";

// Demo documents — unanalyzed, waiting for real AI extraction
export const mockDocuments: Document[] = [
  {
    id: "demo_001",
    name: "Invoice_Acme_Corp_Q4-2025.pdf",
    type: "invoice",
    status: "pending",
    size: 248320,
    pages: 2,
    uploadedAt: "2025-12-18T09:24:00Z",
  },
  {
    id: "demo_002",
    name: "Resume_Sarah_Mitchell_SeniorDev.pdf",
    type: "resume",
    status: "pending",
    size: 186420,
    pages: 3,
    uploadedAt: "2025-12-17T14:12:00Z",
  },
  {
    id: "demo_003",
    name: "Contract_NDA_TechVentures_2025.pdf",
    type: "contract",
    status: "pending",
    size: 524288,
    pages: 8,
    uploadedAt: "2025-12-17T11:30:00Z",
  },
  {
    id: "demo_004",
    name: "Q3_Financial_Report_2025.pdf",
    type: "report",
    status: "pending",
    size: 1048576,
    pages: 24,
    uploadedAt: "2025-12-16T16:45:00Z",
  },
];

// No pre-computed extractions — real AI results come from the backend
export const mockExtractionResults: Record<string, ExtractionResult> = {
};

export const mockAutomations: Automation[] = [
  {
    id: "auto_001",
    name: "Invoice Processing",
    description: "Automatically extract vendor details, amounts, dates, and line items from invoices. Export to accounting software.",
    icon: "FileText",
    documentsProcessed: 1284,
    lastRun: "2025-12-18T09:24:00Z",
    status: "active",
    category: "Finance",
    schema: {
      invoice_number: "string",
      vendor_name: "string",
      total_amount: "currency",
      due_date: "date",
      tax_amount: "currency",
      line_items: "array",
    },
  },
  {
    id: "auto_002",
    name: "Resume Screening",
    description: "Parse CVs and resumes to extract skills, experience, education. Score candidates against job requirements automatically.",
    icon: "User",
    documentsProcessed: 847,
    lastRun: "2025-12-17T14:12:00Z",
    status: "active",
    category: "HR",
    schema: {
      full_name: "string",
      email: "email",
      years_experience: "number",
      skills: "array",
      education: "string",
      current_company: "string",
    },
  },
  {
    id: "auto_003",
    name: "Contract Analyzer",
    description: "Extract key contract clauses, parties, terms, obligations, and risk flags from legal documents.",
    icon: "Scale",
    documentsProcessed: 312,
    lastRun: "2025-12-17T11:30:00Z",
    status: "active",
    category: "Legal",
    schema: {
      parties: "array",
      effective_date: "date",
      expiry_date: "date",
      total_value: "currency",
      obligations: "array",
      termination_clause: "string",
    },
  },
  {
    id: "auto_004",
    name: "Financial Report Parser",
    description: "Extract KPIs, metrics, revenue figures, and trends from quarterly and annual financial reports.",
    icon: "BarChart",
    documentsProcessed: 156,
    lastRun: "2025-12-16T16:45:00Z",
    status: "active",
    category: "Finance",
    schema: {
      revenue: "currency",
      net_profit: "currency",
      growth_rate: "number",
      key_metrics: "array",
      period: "string",
      highlights: "array",
    },
  },
  {
    id: "auto_005",
    name: "Medical Records Extractor",
    description: "Parse patient records, lab results, and medical reports for healthcare data management.",
    icon: "HeartPulse",
    documentsProcessed: 89,
    lastRun: "2025-12-15T09:00:00Z",
    status: "paused",
    category: "Healthcare",
    schema: {
      patient_name: "string",
      date_of_birth: "date",
      diagnosis: "string",
      medications: "array",
      physician: "string",
    },
  },
  {
    id: "auto_006",
    name: "Purchase Order Processor",
    description: "Extract supplier info, item lists, quantities, and pricing from purchase order documents.",
    icon: "ShoppingCart",
    documentsProcessed: 0,
    status: "draft",
    category: "Procurement",
    schema: {
      po_number: "string",
      supplier: "string",
      items: "array",
      total: "currency",
      delivery_date: "date",
    },
  },
];

export const mockActivityItems: ActivityItem[] = [
  {
    id: "act_001",
    type: "extraction",
    documentName: "Invoice_Acme_Corp_Q4-2025.pdf",
    documentType: "invoice",
    timestamp: "2025-12-18T09:24:38Z",
    status: "success",
    details: "14 fields extracted — 98% confidence",
  },
  {
    id: "act_002",
    type: "upload",
    documentName: "Resume_James_Park_DataScientist.pdf",
    documentType: "resume",
    timestamp: "2025-12-18T09:45:00Z",
    status: "success",
    details: "214 KB — processing started",
  },
  {
    id: "act_003",
    type: "export",
    documentName: "Invoice_Acme_Corp_Q4-2025.pdf",
    documentType: "invoice",
    timestamp: "2025-12-18T09:26:00Z",
    status: "success",
    details: "Exported to CSV",
  },
  {
    id: "act_004",
    type: "extraction",
    documentName: "Resume_Sarah_Mitchell_SeniorDev.pdf",
    documentType: "resume",
    timestamp: "2025-12-17T14:12:52Z",
    status: "success",
    details: "22 fields extracted — 96% confidence",
  },
  {
    id: "act_005",
    type: "automation",
    documentName: "Contract_NDA_TechVentures_2025.pdf",
    documentType: "contract",
    timestamp: "2025-12-17T11:31:14Z",
    status: "success",
    details: "Contract Analyzer — 18 clauses identified",
  },
  {
    id: "act_006",
    type: "analysis",
    documentName: "Q3_Financial_Report_2025.pdf",
    documentType: "report",
    timestamp: "2025-12-16T16:47:02Z",
    status: "success",
    details: "31 KPIs extracted — AI summary generated",
  },
  {
    id: "act_007",
    type: "extraction",
    documentName: "Annual_Report_GlobalTech_2024.pdf",
    documentType: "report",
    timestamp: "2025-12-14T15:12:00Z",
    status: "error",
    details: "File too large — processing failed",
  },
  {
    id: "act_008",
    type: "export",
    documentName: "Partnership_Agreement_Nexus_2025.pdf",
    documentType: "contract",
    timestamp: "2025-12-15T08:35:00Z",
    status: "success",
    details: "Exported to JSON + Notion",
  },
];

export const mockAIInsights: AIInsight[] = [
  {
    type: "success",
    title: "Invoice Verified",
    description: "All financial figures cross-validated. Tax calculations are accurate. No anomalies detected.",
    confidence: 98,
  },
  {
    type: "warning",
    title: "Missing Tax ID",
    description: "Vendor tax identification number not found in document. May require manual verification before payment.",
    confidence: 85,
  },
  {
    type: "info",
    title: "Payment Due Soon",
    description: "Invoice INV-2025-4891 is due in 28 days. Recommend scheduling payment this week.",
    confidence: 99,
    entities: ["January 15, 2026", "Net 30", "$12,451.88"],
  },
  {
    type: "info",
    title: "Similar Invoices Found",
    description: "3 previous invoices from Acme Corporation found in database. Average amount: $10,200.",
    confidence: 91,
    entities: ["Acme Corporation", "$10,200 avg"],
  },
];

export const mockDashboardMetrics = [
  { label: "Documents Processed", value: "2,847", change: 18.4, changeLabel: "vs last month", trend: "up" as const, icon: "FileText" },
  { label: "Extraction Accuracy", value: "96.2%", change: 2.1, changeLabel: "vs last month", trend: "up" as const, icon: "Target" },
  { label: "Automations Run", value: "689", change: 31.2, changeLabel: "vs last month", trend: "up" as const, icon: "Zap" },
  { label: "Time Saved", value: "142h", change: 24.8, changeLabel: "vs last month", trend: "up" as const, icon: "Clock" },
];

export const mockChartData = {
  documentTypes: [
    { name: "Invoices", value: 1284, color: "#6366f1" },
    { name: "Resumes", value: 847, color: "#8b5cf6" },
    { name: "Contracts", value: 456, color: "#14b8a6" },
    { name: "Reports", value: 260, color: "#f59e0b" },
  ],
  weeklyActivity: [
    { day: "Mon", documents: 42, extractions: 38 },
    { day: "Tue", documents: 58, extractions: 54 },
    { day: "Wed", documents: 71, extractions: 68 },
    { day: "Thu", documents: 49, extractions: 45 },
    { day: "Fri", documents: 83, extractions: 79 },
    { day: "Sat", documents: 24, extractions: 21 },
    { day: "Sun", documents: 18, extractions: 16 },
  ],
  confidenceTrend: [
    { month: "Jul", accuracy: 91.2 },
    { month: "Aug", accuracy: 92.8 },
    { month: "Sep", accuracy: 93.4 },
    { month: "Oct", accuracy: 94.1 },
    { month: "Nov", accuracy: 95.3 },
    { month: "Dec", accuracy: 96.2 },
  ],
};

